### PR TITLE
Problem with ucfirst when using setlocale(LC_ALL,tr)

### PR DESCRIPTION
**Pull request by moakkaya**
I opened an issue here about that :
https://github.com/spatie/laravel-fractal/issues/108

When the locale setted to tr ucfirst not working as expected because of Turkish alphabet has capitalized i which is İ. 

$resourceClasss returning ```League\Fractal\Resource\item```  instead of ```League\Fractal\Resource\Item```

I don't know it was super necessary but this cost me 8 hours today :)

### CODE REVIEW

**Comment by freekmurze** [comment]
I cannot reproduce your problem. I've cloned your branch, used `uc_first` instead of `self::mb_ucfirst` in `getResource` and the `it_can_perform_a_single_item_with_tr_locale` still passes.

Running

```php
setlocale(LC_ALL, 'tr_TR.UTF-8');
	
echo ucfirst('i');
```

on my system returns `I`.

**Comment by moakkaya** [comment]
The problem is, ucfirst working on my local machine either. But no luck for two different digitalocean centos & ubuntu vps'. 

I've solved the problem with changing LC_ALL to LC_TIME. LC_ALL still not working with ucfirst when locale is setted tr_TR

**Comment by freekmurze** [comment]
Let's see what Travis says. Could you change your PR  so you use `uc_first` instead of `self::mb_ucfirst`.

**Comment by moakkaya** [comment]
If you wish, I can quickly set up a demonstration on my remote machine to let you see what's going on.

**Comment by freekmurze** [comment]
It seems like the tests pass on Travis too. To be honest I don't care too much of what's happening on your particular system (don't take it personally :smile). What I need is a test that fails on Travis to make sure the changes are necessary. For me Travis is like the reference system.

If it fails on your particular server, try to configure it in such a way that the code works (like on Travis). 

I hope you understand my stance on this.

**Comment by moakkaya** [comment]
ok no problem. If you'll have a spare time, please try it any remote server. 

Have a nice day.

**Pull request closed without merging**
